### ISSUE TITLE
NMR does not run

### ISSUE THREAD

**Issue by ycarissan** [pyscf/properties#4]
Dear devs,
example [](https://github.com/pyscf/properties/blob/master/examples/04-nmr.py) does not run. I get the following error message:
```
Traceback (most recent call last):
  File "/home/yannick/script_erreur/./pyscf-properties/examples/04-nmr.py", line 18, in <module>
    nmr.RKS(mf).kernel()
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rhf.py", line 287, in kernel
    return self.shielding(mo1)
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rhf.py", line 297, in shielding
    self.mo10, self.mo_e10 = self.solve_mo1()
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rks.py", line 151, in solve_mo1
    return rhf_nmr.solve_mo1(nmrobj, mo_energy, mo_coeff, mo_occ,
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rhf.py", line 197, in solve_mo1
    h1 = lib.einsum('xpq,pi,qj->xij', nmrobj.get_fock(dm0),
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rks.py", line 124, in get_fock
    h1 -= get_vxc_giao(ni, mol, mf.grids, mf.xc, dm0,
  File "/home/yannick/script_erreur/pyscf-properties/pyscf/prop/nmr/rks.py", line 57, in get_vxc_giao
    for ao, mask, weight, coords \
  File "/home/yannick/script_erreur/pyscf/pyscf/dft/numint.py", line 2673, in _block_loop
    assert blksize % BLKSIZE == 0
AssertionError
```

The attached file allows for the reproduction of this problem, provided that the necessary dependencies for pyscf are installed.
[nmr_error.zip](https://github.com/pyscf/properties/files/11982332/nmr_error.zip)

Let me know if you need more info or if I did somethig wrong.
Yannick

**Comment by ycarissan** [comment]
I am looking into the code. It turns out the call to `block_loop` in the nmr module uses the blksize argument, which is not the case in the pyscf code : 
`grep -Pzo '(?s)block_loop\([^)]*\)' pyscf/pyscf/*/*.py| tr '\0' '\n'|grep blk`
returns nothing, whereas 
`grep -Pzo '(?s)block_loop\([^)]*\)' pyscf/pyscf/*/nmr.py| tr '\0' '\n'|grep blk`
find hits : 
`
pyscf-properties/pyscf/prop/nmr/rks.py:block_loop(mol, grids, nao, ao_deriv, max_memory,
                                 blksize=blksize, buf=buf)
pyscf-properties/pyscf/prop/nmr/rks.py:block_loop(mol, grids, nao, ao_deriv, max_memory,
                                 blksize=blksize, buf=buf)
pyscf-properties/pyscf/prop/nmr/uks.py:block_loop(mol, grids, nao, ao_deriv, max_memory,
                                 blksize=blksize, buf=buf)
pyscf-properties/pyscf/prop/nmr/uks.py:block_loop(mol, grids, nao, ao_deriv, max_memory,
                                 blksize=blksize, buf=buf)
`

To me, this seems to indicate that the blksize argument should be set to None and, despite the comment in `numint.py` line 2668
`    # NOTE to index grids.non0tab, the blksize needs to be an integer
    # multiplier of BLKSIZE
`
the code should run.

I will test it and provide feedback.

**Comment by jghubert** [comment]
Hi,

I encountered the same problem described above. I thought I would add my two cents to the discussion.

I have been testing the example provided in the file https://github.com/pyscf/properties/blob/master/examples/04-nmr.py. It outputs the same error as ycarissan encountered. 

From what I found, the problem comes from the function get_vxc_giao in nmr/rks.py. The line 
`    blksize = min(int(max_memory/12*1e6/8/nao/BLKSIZE)*BLKSIZE, ngrids)
`
ultimately assigns ngris (equal to len(grids.weights)) to blksize. The NMR computation fails because the value is not a multiplier of BLKSIZE. This is contrary to the code in block_loop in numint.py where the value of blksize is guaranteed to be a multiple of BLKSIZE. As ycarissan mentioned, calling block_loop with blksize set to None would solve the problem.

**Comment by steto123** [comment]
Hello Developers,

Is there a solution for this error? I am interested in calculating shielding constants to determine NMR chemical shifts. I am new to Python programming and do not fully understand this discussion.

**Comment by steto123** [comment]
Many, many thanks

**Comment by ycarissan** [comment]
Yes, thanks!
